package com.example.rex;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.rex.Diary;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DIARY".
*/
public class DiaryDao extends AbstractDao<Diary, Long> {

    public static final String TABLENAME = "DIARY";

    /**
     * Properties of entity Diary.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Date = new Property(1, String.class, "date", false, "DATE");
        public final static Property Content = new Property(2, String.class, "content", false, "CONTENT");
        public final static Property Emotion = new Property(3, Integer.class, "emotion", false, "EMOTION");
        public final static Property Weather = new Property(4, Integer.class, "weather", false, "WEATHER");
        public final static Property Year = new Property(5, int.class, "year", false, "YEAR");
        public final static Property Month = new Property(6, int.class, "month", false, "MONTH");
        public final static Property Time = new Property(7, String.class, "time", false, "TIME");
        public final static Property Hidden = new Property(8, Integer.class, "hidden", false, "HIDDEN");
    };


    public DiaryDao(DaoConfig config) {
        super(config);
    }
    
    public DiaryDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DIARY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"DATE\" TEXT NOT NULL ," + // 1: date
                "\"CONTENT\" TEXT NOT NULL ," + // 2: content
                "\"EMOTION\" INTEGER," + // 3: emotion
                "\"WEATHER\" INTEGER," + // 4: weather
                "\"YEAR\" INTEGER NOT NULL ," + // 5: year
                "\"MONTH\" INTEGER NOT NULL ," + // 6: month
                "\"TIME\" TEXT," + // 7: time
                "\"HIDDEN\" INTEGER);"); // 8: hidden
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DIARY\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Diary entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getDate());
        stmt.bindString(3, entity.getContent());
 
        Integer emotion = entity.getEmotion();
        if (emotion != null) {
            stmt.bindLong(4, emotion);
        }
 
        Integer weather = entity.getWeather();
        if (weather != null) {
            stmt.bindLong(5, weather);
        }
        stmt.bindLong(6, entity.getYear());
        stmt.bindLong(7, entity.getMonth());
 
        String time = entity.getTime();
        if (time != null) {
            stmt.bindString(8, time);
        }
 
        Integer hidden = entity.getHidden();
        if (hidden != null) {
            stmt.bindLong(9, hidden);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Diary readEntity(Cursor cursor, int offset) {
        Diary entity = new Diary( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // date
            cursor.getString(offset + 2), // content
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // emotion
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // weather
            cursor.getInt(offset + 5), // year
            cursor.getInt(offset + 6), // month
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // time
            cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8) // hidden
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Diary entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDate(cursor.getString(offset + 1));
        entity.setContent(cursor.getString(offset + 2));
        entity.setEmotion(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setWeather(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setYear(cursor.getInt(offset + 5));
        entity.setMonth(cursor.getInt(offset + 6));
        entity.setTime(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setHidden(cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Diary entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Diary entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
