package com.example.rex;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;

/**
 * Entity mapped to table "DIARY".
 */
public class Diary implements Serializable {

    private Long id;
    /** Not-null value. */
    private String date;
    /** Not-null value. */
    private String content;
    private Integer emotion;
    private Integer weather;
    private int year;
    private int month;
    private String time;
    private Integer hidden;

    public Diary() {
    }

    public Diary(Long id) {
        this.id = id;
    }

    public Diary(Long id, String date, String content, Integer emotion, Integer weather, int year, int month, String time, Integer hidden) {
        this.id = id;
        this.date = date;
        this.content = content;
        this.emotion = emotion;
        this.weather = weather;
        this.year = year;
        this.month = month;
        this.time = time;
        this.hidden = hidden;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getDate() {
        return date;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDate(String date) {
        this.date = date;
    }

    /** Not-null value. */
    public String getContent() {
        return content;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setContent(String content) {
        this.content = content;
    }

    public Integer getEmotion() {
        return emotion;
    }

    public void setEmotion(Integer emotion) {
        this.emotion = emotion;
    }

    public Integer getWeather() {
        return weather;
    }

    public void setWeather(Integer weather) {
        this.weather = weather;
    }

    public int getYear() {
        return year;
    }

    public void setYear(int year) {
        this.year = year;
    }

    public int getMonth() {
        return month;
    }

    public void setMonth(int month) {
        this.month = month;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public Integer getHidden() {
        return hidden;
    }

    public void setHidden(Integer hidden) {
        this.hidden = hidden;
    }

}
