package com.example.rex;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;

/**
 * Entity mapped to table "DIARY".
 */
public class Diary implements Serializable {

    private Long id;
    /** Not-null value. */
    private String date;
    private Integer month;
    private Integer year;
    private String content;

    public Diary() {
    }

    public Diary(Long id) {
        this.id = id;
    }

    public Diary(Long id, String date, Integer month, Integer year, String content) {
        this.id = id;
        this.date = date;
        this.month = month;
        this.year = year;
        this.content = content;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getDate() {
        return date;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDate(String date) {
        this.date = date;
    }

    public Integer getMonth() {
        return month;
    }

    public void setMonth(Integer month) {
        this.month = month;
    }

    public Integer getYear() {
        return year;
    }

    public void setYear(Integer year) {
        this.year = year;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

}
